services:
  - type: web
    name: campus-lost-found
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/campus-lost-found-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: UPLOAD_DIR
        value: uploads
